name: christopherlee
favicon: null
layout_spectrum: 0.18690639012493193
typography_spectrum: 0.5305161064025015
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9209955593105406
  lightness: 0.3979991083033383
  saturation: 0.8193456248845905
  rhythmicContrast: 0.8365593133494258
purpose: []
